server:
  port: 8080
    
spring:
  application:
    name: gateway
      
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/registry/eureka
      
zuul:
  prefix: /api
  ignored-services: "*"
  
  routes:
    crud:
      path: /produtos/**
      service-id: produtos
      strip-prefix: false
      custom-sensitive-headers: true
    
    pagamento:
      path: /pagamento/**
      service-id: pagamento
      strip-prefix: false
      custom-sensitive-headers: true