version: '3.4'
services:
  zipkin:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411
    # command: --logging.level.zipkin2=DEBUG