server:
  port: 8081
  servlet:
    context-path: /produtos
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
    
spring:
  application:
    name: produtos
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/produtos?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    
  rabbitmq:
    host: localhost
    port: 15672
    username: admin
    password: admin
    
  zipkin:
    base-url: http://localhost:9411
    
springdoc:
  swagger-ui:
    path: /swagger-ui.html  
  
crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.produto.routingkey
    
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/registry/eureka